# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/albert.poblador/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_xbar_0/lab3_xbar_0.xci
# IP: The module: 'lab3_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/albert.poblador/lab3/lab3.gen/sources_1/bd/lab3/ip/lab3_xbar_0/lab3_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/albert.poblador/lab3/lab3.srcs/sources_1/bd/lab3/ip/lab3_xbar_0/lab3_xbar_0.xci
# IP: The module: 'lab3_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/albert.poblador/lab3/lab3.gen/sources_1/bd/lab3/ip/lab3_xbar_0/lab3_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab3_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
