# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/lab3.xdc

# Block Designs: bd/lab3/lab3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3 || ORIG_REF_NAME==lab3} -quiet] -quiet

# IP: bd/lab3/ip/lab3_processing_system7_0_0/lab3_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_processing_system7_0_0 || ORIG_REF_NAME==lab3_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_axi_gpio_0_0/lab3_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_axi_gpio_0_0 || ORIG_REF_NAME==lab3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_xbar_0/lab3_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_xbar_0 || ORIG_REF_NAME==lab3_xbar_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_ps7_0_axi_periph_0/lab3_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_rst_ps7_0_111M_0/lab3_rst_ps7_0_111M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_rst_ps7_0_111M_0 || ORIG_REF_NAME==lab3_rst_ps7_0_111M_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_auto_pc_0/lab3_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_auto_pc_0 || ORIG_REF_NAME==lab3_auto_pc_0} -quiet] -quiet

# IP: bd/lab3/ip/lab3_VGA_Controller_0_0/lab3_VGA_Controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab3_VGA_Controller_0_0 || ORIG_REF_NAME==lab3_VGA_Controller_0_0} -quiet] -quiet

# XDC: c:/Users/albert.poblador/lab3/lab3.gen/sources_1/bd/lab3/lab3_ooc.xdc
