# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/albert.poblador/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
# IP: The module: 'lab4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/albert.poblador/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
# IP: The module: 'lab4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
