# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab2/lab2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2 || ORIG_REF_NAME==lab2} -quiet] -quiet

# IP: bd/lab2/ip/lab2_processing_system7_0_0/lab2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_processing_system7_0_0 || ORIG_REF_NAME==lab2_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab2/ip/lab2_axi_timer_0_0/lab2_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_axi_timer_0_0 || ORIG_REF_NAME==lab2_axi_timer_0_0} -quiet] -quiet

# IP: bd/lab2/ip/lab2_ps7_0_axi_periph_0/lab2_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab2/ip/lab2_rst_ps7_0_100M_0/lab2_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab2/ip/lab2_auto_pc_0/lab2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_auto_pc_0 || ORIG_REF_NAME==lab2_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/albert.poblador/lab2/lab2.gen/sources_1/bd/lab2/lab2_ooc.xdc
