# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/albert.poblador/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/lab4_gen_fun_top_0_0.xci
# IP: The module: 'lab4_gen_fun_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/src/sin10K/sin10K.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin10K || ORIG_REF_NAME==sin10K} -quiet] -quiet

# XDC: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/src/test_gen_fun.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_gen_fun_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/albert.poblador/lab4/lab4.srcs/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/lab4_gen_fun_top_0_0.xci
# IP: The module: 'lab4_gen_fun_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/src/sin10K/sin10K.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin10K || ORIG_REF_NAME==sin10K} -quiet] -quiet

# XDC: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/ip/lab4_gen_fun_top_0_0/src/test_gen_fun.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab4_gen_fun_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
