# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab4/lab4.xdc

# Block Designs: bd/lab4/lab4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4 || ORIG_REF_NAME==lab4} -quiet] -quiet

# IP: bd/lab4/ip/lab4_processing_system7_0_0/lab4_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_processing_system7_0_0 || ORIG_REF_NAME==lab4_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_axi_interconnect_0_0/lab4_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_axi_interconnect_0_0 || ORIG_REF_NAME==lab4_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_proc_sys_reset_0_0/lab4_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_proc_sys_reset_0_0 || ORIG_REF_NAME==lab4_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_auto_pc_0/lab4_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_auto_pc_0 || ORIG_REF_NAME==lab4_auto_pc_0} -quiet] -quiet

# IP: bd/lab4/ip/lab4_AD_Converter_0_1/lab4_AD_Converter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_AD_Converter_0_1 || ORIG_REF_NAME==lab4_AD_Converter_0_1} -quiet] -quiet

# IP: bd/lab4/ip/lab4_gen_fun_top_0_0/lab4_gen_fun_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab4_gen_fun_top_0_0 || ORIG_REF_NAME==lab4_gen_fun_top_0_0} -quiet] -quiet

# XDC: c:/Users/albert.poblador/lab4/lab4.gen/sources_1/bd/lab4/lab4_ooc.xdc
