webtalk_init -webtalk_dir C:/Users/albert.poblador/ip_lab3/ip_repo/edit_VGA_Controller_v1_0.sim/sim_1/behav/xsim/xsim.dir/VGA_Controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 11 09:59:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174215380_174171543_210742938_167" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a246663f-a84d-4ba3-ac2d-f507b32343ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c540b8899c534d3eb95af9f4975b4a29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "16.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14092_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2131075759 -regid "174215380_174171543_210742938_167" -xml C:/Users/albert.poblador/ip_lab3/ip_repo/edit_VGA_Controller_v1_0.sim/sim_1/behav/xsim/xsim.dir/VGA_Controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/albert.poblador/ip_lab3/ip_repo/edit_VGA_Controller_v1_0.sim/sim_1/behav/xsim/xsim.dir/VGA_Controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/albert.poblador/ip_lab3/ip_repo/edit_VGA_Controller_v1_0.sim/sim_1/behav/xsim/xsim.dir/VGA_Controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
